data_backend: panda
run:
    - name: diabete_analysis_1
      data_files:
        - ["diabetes.arff", "arff"]
      analyses:
         oneR: 
            enabled: true
            options:
               class_col: "class"
         zeroR: 
            enabled: true
            options:
               class_col: "class"
         c45: 
            enabled: true
            options:
               class_col: "class"
               max_depth: 5
               min_instances_per_node: 1
               impurity: "entropy"
               test_size: 0.3
               verbose: true
               