data_backend: pandas
run:
    - name: students_analysis
      data_files:
        - ["student.csv", "csv", "student_1", ";"]
      analyses:
         correlation:
            enabled: true
            attributes:
               - ["school", "nominal", "G3", "continuous", "Eta"]
               - ["sex", "nominal", "G3", "continuous", "Eta"]
               - ["age", "nominal", "G3", "continuous", "Eta"]
               - ["address", "nominal", "G3", "continuous", "Eta"]
               - ["famsize", "nominal", "G3", "continuous", "Eta"]
               - ["Pstatus", "nominal", "G3", "continuous", "Eta"]
               - ["Medu", "ordinal", "G3", "continuous", "Spearman"]
               - ["Fedu", "ordinal", "G3", "continuous", "Spearman"]
               - ["Mjob", "nominal", "G3", "continuous", "Eta"]
               - ["Fjob", "nominal", "G3", "continuous", "Eta"]
               - ["reason", "nominal", "G3", "continuous", "Eta"]
               - ["guardian", "nominal", "G3", "continuous", "Eta"]
               - ["traveltime", "ordinal", "G3", "continuous", "Spearman"]
               - ["studytime", "ordinal", "G3", "continuous", "Spearman"]
               - ["failures", "ordinal", "G3", "continuous", "Spearman"]
               - ["schoolsup", "nominal", "G3", "continuous", "Eta"]
               - ["famsup", "nominal", "G3", "continuous", "Eta"]
               - ["paid", "nominal", "G3", "continuous", "Eta"]
               - ["activities", "nominal", "G3", "continuous", "Eta"]
               - ["nursery", "nominal", "G3", "continuous", "Eta"]
               - ["higher", "nominal", "G3", "continuous", "Eta"]
               - ["internet", "nominal", "G3", "continuous", "Eta"]
               - ["romantic", "nominal", "G3", "continuous", "Eta"]
               - ["famrel", "ordinal", "G3", "continuous", "Spearman"]
               - ["freetime", "ordinal", "G3", "continuous", "Spearman"]
               - ["goout", "ordinal", "G3", "continuous", "Spearman"]
               - ["Dalc", "ordinal", "G3", "continuous", "Spearman"]
               - ["Walc", "ordinal", "G3", "continuous", "Spearman"]
               - ["health", "ordinal", "G3", "continuous", "Spearman"]
               - ["absences", "continuous", "G3", "continuous", "Spearman"]
               - ["G1", "continuous", "G3", "continuous", "Spearman"]
               - ["G2", "continuous", "G3", "continuous", "Spearman"]
               - ["G1", "continuous", "G2", "continuous", "Spearman"]
         shapiro_wilk:
            enabled: true
            attributes:
               - ["absences", 0.05]
               - ["G1", 0.05]
               - ["G2", 0.05]
               - ["G3", 0.05]            
         cramers_v:
            enabled: true
            attributes:
               - ["school", "reason"]
         oneR: 
            enabled: false
            options:
               class_col: "class"
         zeroR: 
            enabled: false
            options:
               class_col: "class"
         c45: 
            enabled: false
            options:
               class_col: "class"
               max_depth: 5
               min_instances_per_node: 1
               impurity: "entropy"
               test_size: 0.3
               verbose: true
               